name: cyber_interigence
description: "A new Flutter project."

# pub.dev 申請はないのでNoneのまま.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# バージョン履歴
# 1.0.0+1: AppStore申請版
# 1.0.1+2: GooglePlayStore申請版：PDF表示を別ライブラリコールへ変更,Build時のVer13対応（広告定義）
# 
version: 1.0.2+3

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies 
dependencies:
  flutter:
    sdk: flutter


  # 特記事項
  # firebase関連のバージョンは1.0.0構築時に確認されたもの
  cupertino_icons: ^1.0.6
  http:
  intl: 
  webfeed_plus:
  html: 
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  freezed_annotation: 
  shared_preferences: 
  google_fonts: 
  flutter_riverpod: 
  hooks_riverpod:
  flutter_local_notifications:
  introduction_screen:  
  loading_animation_widget: 
  flutter_launcher_icons:
  flutter_cached_pdfview:
  webview_flutter:
  synchronized:

  # 特記事項
  # 
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  riverpod_lint:
  freezed: 
  json_serializable: 
  riverpod_generator:
  flutter_native_splash:

  # The "flutter_lints" 
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # リソース関連の定義
  assets:
    - images/
    - images/servicel2w.png
    - images/servicel2b.png

  # アイコンの定義
  # flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  image_path: "images/launcher/SecAplIconV11024.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "images/launcher/icon_adaptive_background.png"
  adaptive_icon_foreground: "images/launcher/SecAplIconV1108.png"

  # 起動時のSplash表示
flutter_native_splash:
  color: '#add8e6'
  image: 'images/splash/ApplicationFlash.png'
  color_dark: '#262626'
  image_dark: 'images/splash/ApplicationFlash.png'
  fullscreen: false
  android_12:
    icon_background_color: '#add8e6'
    image: 'images/splash/ApplicationFlash.png'
    icon_background_color_dark: '#262626'
    image_dark: 'images/splash/ApplicationFlash.png'

  # フォントセットは内部で指定しているのでここでは定義しない
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
